server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/runners
    username: postgres
    password: 1000239
    driver: com.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
